spring:
  datasource:
    url: jdbc:mysql://localhost:3307/empmgmt
    username: nitin
    password: ENC(pZgwFjsJ5zhz/u+8/D11WEfGd3e9HZPh)
  cloud:
    config:
      profile: dev
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibenate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    ip-address: localhost
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/